server:
  port: ${PORT:8080}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}  # Asegurar ID único

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: capacidad-service
          uri: lb://capacidad-service
          predicates:
            - Path=/apicapacidad/**
        - id: camion-service
          uri: lb://camion-service
          predicates:
            - Path=/apicamion/**
        - id: cargo-service
          uri: lb://cargo-service
          predicates:
            - Path=/apicargo/**
        - id: entrega-service
          uri: lb://entrega-service
          predicates:
            - Path=/apientrega/**
        - id: estadopicking-service
          uri: lb://estadopicking-service
          predicates:
            - Path=/apiestadopicking/**
        - id: estadoentrega-service
          uri: lb://estadoentrega-service
          predicates:
            - Path=/apiestadoentrega/**
        - id: excel-service
          uri: lb://excel-service
          predicates:
            - Path=/api/v1/recopilar/**
        - id: flete-service
          uri: lb://flete-service
          predicates:
            - Path=/apiflete/**
        - id: personal-service
          uri: lb://personal-service
          predicates:
            - Path=/apipersonal/**
        - id: picking-service
          uri: lb://picking-service
          predicates:
            - Path=/apipicking/**
        - id: rolcargo-service
          uri: lb://rolcargo-service
          predicates:
            - Path=/apirolcargo/**
        - id: ruta-service
          uri: lb://ruta-service
          predicates:
            - Path=/apiruta/**
        - id: tarifario-service
          uri: lb://tarifario-service
          predicates:
            - Path=/apitarifario/**
        - id: tienda-service
          uri: lb://tienda-service
          predicates:
            - Path=/apitienda/**
        - id: tipoflete-service
          uri: lb://tipoflete-service
          predicates:
            - Path=/apitipoflete/**
        - id: viaje-service
          uri: lb://viaje-service
          predicates:
            - Path=/apiviaje/**

      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
