server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  cloud:
    gateway: 
      discovery:
        locator:
          enabled: true
      routes: 
        - id: camion-service
          uri: lb://CAMION-SERVICE
          predicates:
            - Path=/apicamion/**

