server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    instance-id: gateway-service:${spring.application.instance_id:${random.value}}  # Asegurar ID único

spring:
  cloud:
    gateway: 
      discovery:
        locator:
          enabled: true
      routes: 
        - id: capacidad-service
          uri: lb://CAPACIDAD-SERVICE  # Usar el balanceador de carga si se registra en Eureka
          predicates:
            - Path=/apicapacidad/**



